apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: example-deployment-ingress
  namespace: example-user
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "certificate-issuer"
spec:
  tls:
  - hosts:
    - example-endpoint.juliustens.eu
    secretName: example-deployment-tls
  rules:
  - host: example-endpoint.juliustens.eu
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: example-deployment
            port:
              number: 80
