name: Build, push and deploy
on:
  push:
    branches: [ master, action-test ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: public-transport/kubernetes-setup/deploy-basic-service@gh-action
      with:
        docker-access-token: ${{ secrets.DOCKER_ACCESS_TOKEN }}
        kubernetes-config: ${{ secrets.KUBERNETES_CONFIG }}
